[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_50 = "7Be3MS2o8A46F8UftQ1hj1q6bAKNxyjwvmUQPKG2JnVu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/booker/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
